---
output: github_document
---

```{r echo=FALSE, include=FALSE}
library(tidyverse)
library(gh)
library(lubridate)
library(knitr)

query = "ggplot+theme"
get_repos <- function(query) {
  qstr <- glue::glue("GET /search/repositories?q={query}")
  accept_hdr <- "application/vnd.github.mercy-preview+json"
  res <- gh(qstr, .accept = accept_hdr)
  pages <- ceiling(res$total_count / 30)
  items <- c(res$items)
  for (i in 2:pages) {
    res <- gh(qstr, page = i, .accept = accept_hdr)
    Sys.sleep(10) # to avoid hitting the API limit
    items <- c(items, res$items)
  }
  return(items)
}

# get all repos that mention "ggplot2" and "theme"
res1 <- get_repos("ggplot2+theme")
Sys.sleep(30) # to avoid hitting the API limit
res2 <- get_repos("ggplot2+style")
Sys.sleep(30) # to avoid hitting the API limit
# topic search
# ggplot2-theme and ggplot2-themes
res3 <- get_repos("topic:ggplot2-themes")
Sys.sleep(30) # to avoid hitting the API limit
res4 <- get_repos("topic:ggplot2-theme")

res_items <- c(res1, res2, res3, res4)

fix_null <- function(x) {
  ifelse(is_null(x), "", x)
}

github_ggplot2_themes <- tibble(
  name = character(),
  repo_url = character(),
  description = character(),
  homepage = character(),
  license = character(),
  created = character(),
  updated = character()
)

# list of the repos to filter off
repos_no_themes <- c(
  "jmcastagnetto/ggplot2_themes_in_github",
  "dannguyen/matplotlib-styling-tutorial",
  "davidhuh/plot_templates",
  "jkeirstead/r-slopegraph",
  "ArtPoon/ggfree",
  "foxnic/US-Mass-Shootings-Analysis",
  "guiastrennec/ggplus",
  "threecifanggen/ggplotly",
  "edawson/tidysig",
  "elabuel-o/xkcd-graphics",
  "pobch/ggplot2_practicing",
  "rensa/ggclump",
  "eclarke/ggbeeswarm",
  "GeekOnAcid/geom_rug2",
  "cemalley/data-viz",
  "onlyphantom/rgraphics",
  "sethbilliau/HODP-styleguide",
  "uplotnik/TidyVerseAssignment.md",
  "binmishr/Wrangling_and_Visualizing_Musical_Data_R"
)

for (item in res_items) {
  # filter off repos w/o themes/styles
  if (item$full_name %in% repos_no_themes) {
    next
  }
  github_ggplot2_themes <- bind_rows(
    github_ggplot2_themes,
    tibble(
      name = item$name,
      repo_url = item$html_url,
      description = fix_null(item$description),
      homepage = fix_null(item$homepage),
      license = fix_null(item$license$name),
      created = item$created_at,
      updated = item$updated_at,
    )
  )
}
github_ggplot2_themes <- github_ggplot2_themes %>%
  distinct() %>%
  arrange(name, created)
last_generated <- now(tzone = "UTC")
# save csv
write_csv(
  github_ggplot2_themes,
  path = "ggplot2_themes_in_github.csv"
)
```

# List of github repos with (possible) ggplot2 themes

**Last generated on** `r last_generated` (UTC)

- This list is generated using the github API, so it relies on the descriptions and tags in each repository
- Get the [data in CSV format](ggplot2_themes_in_github.csv)
- If you find a repo that doesn't contain a theme, submit an issue so I can add it to the filter

```{r echo=FALSE, results}
kable(github_ggplot2_themes %>%
  rownames_to_column("item"),
      format = "markdown"
      )
```


*License*: MIT
