# Based on https://fromthebottomoftheheap.net/2020/04/30/rendering-your-readme-with-github-actions/
on:
  schedule:
    - cron: '0 2 * * 0'  # run every sunday at 02:00
  push:
    paths:
      - README.Rmd

name: Render README

jobs:
  render:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Set up R
        uses: r-lib/actions/setup-r@v1

      - name: Install needed libraries
        run: RScript -e 'install.packages(c("tidyverse", "lubridate", "knitr", "rmarkdown", "gh")'

      - name: Render README from RMarkdown
        run: Rscript build-readme.R

      - name: Commit results
        run: |
          git commit -m 'Re-build README.md' README.md || echo "No changes to commit"
          git push origin || echo "No changes to commit"
